/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
window.onload = colapseOnload;
function colapseOnload(){
       colapseAll();
       colapseButton();
}
function colapseAll(){
$(document).ready(function(){    
        $(".ul-hide").hide("slow");
        $(".ul-hide-show").hide("slow");
});
}
$(document).ready(function(){
    $("#colapse").click(function(){
        $(".ul-hide").hide("slow");
        $(".ul-hide-show").hide("slow");
    });
});
$(document).ready(function(){
    $("#expand").click(function(){
        $(".ul-hide").show("slow");
        $(".ul-hide-show").show("slow");
    });
});

$(document).ready(function(){
    $("#img-id-1").click(function(){
        $("#id-1").show("slow");
    });
});
$(document).ready(function(){
    $("#img-id-2").click(function(){
        $("#id-1").hide("slow");
    });
});
$(document).ready(function(){
    $("#img-id-3").click(function(){
        $("#id-2").show("slow");
    });
});
$(document).ready(function(){
    $("#img-id-4").click(function(){
        $("#id-2").hide("slow");
    });
});
$(document).ready(function(){
    $("#img-id-5").click(function(){
        $("#id-3").show("slow");
    });
});
$(document).ready(function(){
    $("#img-id-6").click(function(){
        $("#id-3").hide("slow");
    });
});
$(document).ready(function(){
    $("#img-id-7").click(function(){
        $("#id-4").show("slow");
    });
});
$(document).ready(function(){
    $("#img-id-8").click(function(){
        $("#id-4").hide("slow");
    });
});
$(document).ready(function(){
    $("#img-id-9").click(function(){
        $("#id-5").show("slow");
    });
});
$(document).ready(function(){
    $("#img-id-10").click(function(){
        $("#id-5").hide("slow");
    });
});
$(document).ready(function(){
    $("#img-id-11").click(function(){
        $("#id-6").show("slow");
    });
});
$(document).ready(function(){
    $("#img-id-12").click(function(){
        $("#id-6").hide("slow");
    });
});
$(document).ready(function(){
    $("#img-id-13").click(function(){
        $("#id-7").show("slow");
    });
});
$(document).ready(function(){
    $("#img-id-14").click(function(){
        $("#id-7").hide("slow");
    });
});
$(document).ready(function(){
    $("#img-id-15").click(function(){
        $("#id-8").show("slow");
    });
});
$(document).ready(function(){
    $("#img-id-16").click(function(){
        $("#id-8").hide("slow");
    });
});
$(document).ready(function(){
    $("#img-id-17").click(function(){
        $("#id-9").show("slow");
    });
});
$(document).ready(function(){
    $("#img-id-18").click(function(){
        $("#id-9").hide("slow");
    });
});
$(document).ready(function(){
    $("#img-id-19").click(function(){
        $("#id-10").show("slow");
    });
});
$(document).ready(function(){
    $("#img-id-20").click(function(){
        $("#id-10").hide("slow");
    });
});
$(document).ready(function(){
    $("#img-id-21").click(function(){
        $("#id-11").show("slow");
    });
});
$(document).ready(function(){
    $("#img-id-22").click(function(){
        $("#id-11").hide("slow");
    });
});
$(document).ready(function(){
    $("#img-id-23").click(function(){
        $("#id-12").show("slow");
    });
});
$(document).ready(function(){
    $("#img-id-24").click(function(){
        $("#id-12").hide("slow");
    });
});
$(document).ready(function(){
    $("#img-id-25").click(function(){
        $("#id-13").show("slow");
    });
});
$(document).ready(function(){
    $("#img-id-26").click(function(){
        $("#id-13").hide("slow");
    });
});
$(document).ready(function(){
    $("#img-id-27").click(function(){
        $("#id-14").show("slow");
    });
});
$(document).ready(function(){
    $("#img-id-28").click(function(){
        $("#id-14").hide("slow");
    });
});
$(document).ready(function(){
    $("#img-id-29").click(function(){
        $("#id-15").show("slow");
    });
});
$(document).ready(function(){
    $("#img-id-30").click(function(){
        $("#id-15").hide("slow");
    });
});
$(document).ready(function(){
    $("#img-id-31").click(function(){
        $("#id-16").show("slow");
    });
});
$(document).ready(function(){
    $("#img-id-32").click(function(){
        $("#id-16").hide("slow");
    });
});
$(document).ready(function(){
    $("#img-id-33").click(function(){
        $("#id-17").show("slow");
    });
});
$(document).ready(function(){
    $("#img-id-34").click(function(){
        $("#id-17").hide("slow");
    });
});
$(document).ready(function(){
    $("#img-id-35").click(function(){
        $("#id-18").show("slow");
    });
});
$(document).ready(function(){
    $("#img-id-36").click(function(){
        $("#id-18").hide("slow");
    });
});
$(document).ready(function(){
    $("#img-id-37").click(function(){
        $("#id-19").show("slow");
    });
});
$(document).ready(function(){
    $("#img-id-38").click(function(){
        $("#id-19").hide("slow");
    });
});
$(document).ready(function(){
    $("#img-id-39").click(function(){
        $("#id-20").show("slow");
    });
});
$(document).ready(function(){
    $("#img-id-40").click(function(){
        $("#id-20").hide("slow");
    });
});
$(document).ready(function(){
    $("#img-id-41").click(function(){
        $("#id-21").show("slow");
    });
});
$(document).ready(function(){
    $("#img-id-42").click(function(){
        $("#id-21").hide("slow");
    });
});
$(document).ready(function(){
    $("#img-id-43").click(function(){
        $("#id-22").show("slow");
    });
});
$(document).ready(function(){
    $("#img-id-44").click(function(){
        $("#id-22").hide("slow");
    });
});
$(document).ready(function(){
    $("#img-id-45").click(function(){
        $("#id-23").show("slow");
    });
});
$(document).ready(function(){
    $("#img-id-46").click(function(){
        $("#id-23").hide("slow");
    });
});
$(document).ready(function(){
    $("#img-id-47").click(function(){
        $("#id-24").show("slow");
    });
});
$(document).ready(function(){
    $("#img-id-48").click(function(){
        $("#id-24").hide("slow");
    });
});
$(document).ready(function(){
    $("#img-id-49").click(function(){
        $("#id-25").show("slow");
    });
});
$(document).ready(function(){
    $("#img-id-50").click(function(){
        $("#id-25").hide("slow");
    });
});
$(document).ready(function(){
    $("#img-id-51").click(function(){
        $("#id-26").show("slow");
    });
});
$(document).ready(function(){
    $("#img-id-52").click(function(){
        $("#id-26").hide("slow");
    });
});
$(document).ready(function(){
    $("#img-id-53").click(function(){
        $("#id-27").show("slow");
    });
});
$(document).ready(function(){
    $("#img-id-54").click(function(){
        $("#id-27").hide("slow");
    });
});
$(document).ready(function(){
    $("#img-id-55").click(function(){
        $("#id-28").show("slow");
    });
});
$(document).ready(function(){
    $("#img-id-56").click(function(){
        $("#id-28").hide("slow");
    });
});
$(document).ready(function(){
    $("#img-id-57").click(function(){
        $("#id-29").show("slow");
    });
});
$(document).ready(function(){
    $("#img-id-58").click(function(){
        $("#id-29").hide("slow");
    });
});
$(document).ready(function(){
    $("#img-id-59").click(function(){
        $("#id-30").show("slow");
    });
});
$(document).ready(function(){
    $("#img-id-60").click(function(){
        $("#id-30").hide("slow");
    });
});
$(document).ready(function(){
    $("#img-id-61").click(function(){
        $("#id-31").show("slow");
    });
    $("#img-id-62").click(function(){
        $("#id-31").hide("slow");
    });
    $("#img-id-63").click(function(){
        $("#id-32").show("slow");
    });
    $("#img-id-64").click(function(){
        $("#id-32").hide("slow");
    });
    $("#img-id-65").click(function(){
        $("#id-33").show("slow");
    });
    $("#img-id-66").click(function(){
        $("#id-33").hide("slow");
    });
    $("#img-id-67").click(function(){
        $("#id-34").show("slow");
    });
    $("#img-id-68").click(function(){
        $("#id-34").hide("slow");
    });
    $("#img-id-69").click(function(){
        $("#id-35").show("slow");
    });
    $("#img-id-70").click(function(){
        $("#id-35").hide("slow");
    });
    $("#img-id-71").click(function(){
        $("#id-36").show("slow");
    });
    $("#img-id-72").click(function(){
        $("#id-36").hide("slow");
    });
    $("#img-id-73").click(function(){
        $("#id-37").show("slow");
    });
    $("#img-id-74").click(function(){
        $("#id-37").hide("slow");
    });
    $("#img-id-75").click(function(){
        $("#id-38").show("slow");
    });
    $("#img-id-76").click(function(){
        $("#id-38").hide("slow");
    });
    $("#img-id-77").click(function(){
        $("#id-39").show("slow");
    });
    $("#img-id-78").click(function(){
        $("#id-39").hide("slow");
    });
    $("#img-id-79").click(function(){
        $("#id-40").show("slow");
    });
    $("#img-id-80").click(function(){
        $("#id-40").hide("slow");
    });
    $("#img-id-81").click(function(){
        $("#id-41").show("slow");
    });
    $("#img-id-82").click(function(){
        $("#id-41").hide("slow");
    });
    $("#img-id-83").click(function(){
        $("#id-42").show("slow");
    });
    $("#img-id-84").click(function(){
        $("#id-42").hide("slow");
    });
    $("#img-id-85").click(function(){
        $("#id-43").show("slow");
    });
    $("#img-id-86").click(function(){
        $("#id-43").hide("slow");
    });
    $("#img-id-87").click(function(){
        $("#id-44").show("slow");
    });
    $("#img-id-88").click(function(){
        $("#id-44").hide("slow");
    });
    $("#img-id-89").click(function(){
        $("#id-45").show("slow");
    });
    $("#img-id-90").click(function(){
        $("#id-45").hide("slow");
    });
    $("#img-id-91").click(function(){
        $("#id-46").show("slow");
    });
    $("#img-id-92").click(function(){
        $("#id-46").hide("slow");
    });
    $("#img-id-93").click(function(){
        $("#id-47").show("slow");
    });
    $("#img-id-94").click(function(){
        $("#id-47").hide("slow");
    });
    $("#img-id-95").click(function(){
        $("#id-48").show("slow");
    });
    $("#img-id-96").click(function(){
        $("#id-48").hide("slow");
    });
    $("#img-id-97").click(function(){
        $("#id-49").show("slow");
    });
    $("#img-id-98").click(function(){
        $("#id-49").hide("slow");
    });
    $("#img-id-99").click(function(){
        $("#id-50").show("slow");
    });
    $("#img-id-100").click(function(){
        $("#id-50").hide("slow");
    });
    $("#img-id-101").click(function(){
        $("#id-51").show("slow");
    });
    $("#img-id-102").click(function(){
        $("#id-51").hide("slow");
    });
    $("#img-id-103").click(function(){
        $("#id-52").show("slow");
    });
    $("#img-id-104").click(function(){
        $("#id-52").hide("slow");
    });
    $("#img-id-105").click(function(){
        $("#id-53").show("slow");
    });
    $("#img-id-106").click(function(){
        $("#id-53").hide("slow");
    });
    $("#img-id-107").click(function(){
        $("#id-54").show("slow");
    });
    $("#img-id-108").click(function(){
        $("#id-54").hide("slow");
    });
    $("#img-id-109").click(function(){
        $("#id-55").show("slow");
    });
    $("#img-id-110").click(function(){
        $("#id-55").hide("slow");
    });
    $("#img-id-111").click(function(){
        $("#id-56").show("slow");
    });
    $("#img-id-112").click(function(){
        $("#id-56").hide("slow");
    });
    $("#img-id-113").click(function(){
        $("#id-57").show("slow");
    });
    $("#img-id-114").click(function(){
        $("#id-57").hide("slow");
    });
    $("#img-id-115").click(function(){
        $("#id-58").show("slow");
    });
    $("#img-id-116").click(function(){
        $("#id-58").hide("slow");
    });
    $("#img-id-117").click(function(){
        $("#id-59").show("slow");
    });
    $("#img-id-118").click(function(){
        $("#id-59").hide("slow");
    });
    $("#img-id-119").click(function(){
        $("#id-60").show("slow");
    });
    $("#img-id-120").click(function(){
        $("#id-60").hide("slow");
    });    
    $("#img-id-121").click(function(){
        $("#id-61").show("slow");
    });
    $("#img-id-122").click(function(){
        $("#id-61").hide("slow");
    });
    $("#img-id-123").click(function(){
        $("#id-62").show("slow");
    });
    $("#img-id-124").click(function(){
        $("#id-62").hide("slow");
    });
    $("#img-id-125").click(function(){
        $("#id-63").show("slow");
    });
    $("#img-id-126").click(function(){
        $("#id-63").hide("slow");
    });
    $("#img-id-127").click(function(){
        $("#id-64").show("slow");
    });
    $("#img-id-128").click(function(){
        $("#id-64").hide("slow");
    });
    $("#img-id-129").click(function(){
        $("#id-65").show("slow");
    });
    $("#img-id-130").click(function(){
        $("#id-65").hide("slow");
    });
    $("#img-id-131").click(function(){
        $("#id-66").show("slow");
    });
    $("#img-id-132").click(function(){
        $("#id-66").hide("slow");
    });
    $("#img-id-133").click(function(){
        $("#id-67").show("slow");
    });
    $("#img-id-134").click(function(){
        $("#id-67").hide("slow");
    });
    $("#img-id-135").click(function(){
        $("#id-68").show("slow");
    });
    $("#img-id-136").click(function(){
        $("#id-68").hide("slow");
    });
    $("#img-id-137").click(function(){
        $("#id-69").show("slow");
    });
    $("#img-id-138").click(function(){
        $("#id-69").hide("slow");
    });
    $("#img-id-139").click(function(){
        $("#id-70").show("slow");
    });
    $("#img-id-140").click(function(){
        $("#id-70").hide("slow");
    });
    $("#img-id-141").click(function(){
        $("#id-71").show("slow");
    });
    $("#img-id-142").click(function(){
        $("#id-71").hide("slow");
    });
    $("#img-id-143").click(function(){
        $("#id-72").show("slow");
    });
    $("#img-id-144").click(function(){
        $("#id-72").hide("slow");
    });
    $("#img-id-145").click(function(){
        $("#id-73").show("slow");
    });
    $("#img-id-146").click(function(){
        $("#id-73").hide("slow");
    });
    $("#img-id-147").click(function(){
        $("#id-74").show("slow");
    });
    $("#img-id-148").click(function(){
        $("#id-74").hide("slow");
    });
    $("#img-id-149").click(function(){
        $("#id-75").show("slow");
    });
    $("#img-id-150").click(function(){
        $("#id-75").hide("slow");
    });
    $("#img-id-151").click(function(){
        $("#id-76").show("slow");
    });
    $("#img-id-152").click(function(){
        $("#id-76").hide("slow");
    });
    $("#img-id-153").click(function(){
        $("#id-77").show("slow");
    });
    $("#img-id-154").click(function(){
        $("#id-77").hide("slow");
    });
    $("#img-id-155").click(function(){
        $("#id-78").show("slow");
    });
    $("#img-id-156").click(function(){
        $("#id-78").hide("slow");
    });
    $("#img-id-157").click(function(){
        $("#id-79").show("slow");
    });
    $("#img-id-158").click(function(){
        $("#id-79").hide("slow");
    });
    $("#img-id-159").click(function(){
        $("#id-80").show("slow");
    });
    $("#img-id-160").click(function(){
        $("#id-80").hide("slow");
    });
    $("#img-id-161").click(function(){
        $("#id-81").show("slow");
    });
    $("#img-id-162").click(function(){
        $("#id-81").hide("slow");
    });
    $("#img-id-163").click(function(){
        $("#id-82").show("slow");
    });
    $("#img-id-164").click(function(){
        $("#id-82").hide("slow");
    });
    $("#img-id-165").click(function(){
        $("#id-83").show("slow");
    });
    $("#img-id-166").click(function(){
        $("#id-83").hide("slow");
    });
    $("#img-id-167").click(function(){
        $("#id-84").show("slow");
    });
    $("#img-id-168").click(function(){
        $("#id-84").hide("slow");
    });
    $("#img-id-169").click(function(){
        $("#id-85").show("slow");
    });
    $("#img-id-170").click(function(){
        $("#id-85").hide("slow");
    });
    $("#img-id-171").click(function(){
        $("#id-86").show("slow");
    });
    $("#img-id-172").click(function(){
        $("#id-86").hide("slow");
    });
    $("#img-id-173").click(function(){
        $("#id-87").show("slow");
    });
    $("#img-id-174").click(function(){
        $("#id-87").hide("slow");
    });
    $("#img-id-175").click(function(){
        $("#id-88").show("slow");
    });
    $("#img-id-176").click(function(){
        $("#id-88").hide("slow");
    });
    $("#img-id-177").click(function(){
        $("#id-89").show("slow");
    });
    $("#img-id-178").click(function(){
        $("#id-89").hide("slow");
    });
    $("#img-id-179").click(function(){
        $("#id-90").show("slow");
    });
    $("#img-id-180").click(function(){
        $("#id-90").hide("slow");
    });
    
    $("#img-id-181").click(function(){
        $("#id-91").show("slow");
    });
    $("#img-id-182").click(function(){
        $("#id-91").hide("slow");
    });
    $("#img-id-183").click(function(){
        $("#id-92").show("slow");
    });
    $("#img-id-184").click(function(){
        $("#id-92").hide("slow");
    });
    $("#img-id-185").click(function(){
        $("#id-93").show("slow");
    });
    $("#img-id-186").click(function(){
        $("#id-93").hide("slow");
    });
    $("#img-id-187").click(function(){
        $("#id-94").show("slow");
    });
    $("#img-id-188").click(function(){
        $("#id-94").hide("slow");
    });
    $("#img-id-189").click(function(){
        $("#id-95").show("slow");
    });
    $("#img-id-190").click(function(){
        $("#id-95").hide("slow");
    });
    $("#img-id-191").click(function(){
        $("#id-96").show("slow");
    });
    $("#img-id-192").click(function(){
        $("#id-96").hide("slow");
    });
    $("#img-id-193").click(function(){
        $("#id-97").show("slow");
    });
    $("#img-id-194").click(function(){
        $("#id-97").hide("slow");
    });
    $("#img-id-195").click(function(){
        $("#id-98").show("slow");
    });
    $("#img-id-196").click(function(){
        $("#id-98").hide("slow");
    });
    $("#img-id-197").click(function(){
        $("#id-99").show("slow");
    });
    $("#img-id-198").click(function(){
        $("#id-99").hide("slow");
    });
    $("#img-id-199").click(function(){
        $("#id-100").show("slow");
    });
    $("#img-id-200").click(function(){
        $("#id-100").hide("slow");
    });
    $("#img-id-201").click(function(){
        $("#id-101").show("slow");
    });
    $("#img-id-202").click(function(){
        $("#id-101").hide("slow");
    });
    $("#img-id-203").click(function(){
        $("#id-102").show("slow");
    });
    $("#img-id-204").click(function(){
        $("#id-102").hide("slow");
    });
    $("#img-id-205").click(function(){
        $("#id-103").show("slow");
    });
    $("#img-id-206").click(function(){
        $("#id-103").hide("slow");
    });
    $("#img-id-207").click(function(){
        $("#id-104").show("slow");
    });
    $("#img-id-208").click(function(){
        $("#id-104").hide("slow");
    });
    $("#img-id-209").click(function(){
        $("#id-105").show("slow");
    });
    $("#img-id-210").click(function(){
        $("#id-105").hide("slow");
    });
    $("#img-id-211").click(function(){
        $("#id-106").show("slow");
    });
    $("#img-id-212").click(function(){
        $("#id-106").hide("slow");
    });
    $("#img-id-213").click(function(){
        $("#id-107").show("slow");
    });
    $("#img-id-214").click(function(){
        $("#id-107").hide("slow");
    });
    $("#img-id-215").click(function(){
        $("#id-108").show("slow");
    });
    $("#img-id-216").click(function(){
        $("#id-108").hide("slow");
    });
    $("#img-id-217").click(function(){
        $("#id-109").show("slow");
    });
    $("#img-id-218").click(function(){
        $("#id-109").hide("slow");
    });
    $("#img-id-219").click(function(){
        $("#id-110").show("slow");
    });
    $("#img-id-220").click(function(){
        $("#id-110").hide("slow");
    });
    $("#img-id-221").click(function(){
        $("#id-111").show("slow");
    });
    $("#img-id-222").click(function(){
        $("#id-111").hide("slow");
    });
    $("#img-id-223").click(function(){
        $("#id-112").show("slow");
    });
    $("#img-id-224").click(function(){
        $("#id-112").hide("slow");
    });
    $("#img-id-225").click(function(){
        $("#id-113").show("slow");
    });
    $("#img-id-226").click(function(){
        $("#id-113").hide("slow");
    });
    $("#img-id-227").click(function(){
        $("#id-114").show("slow");
    });
    $("#img-id-228").click(function(){
        $("#id-114").hide("slow");
    });
    $("#img-id-229").click(function(){
        $("#id-115").show("slow");
    });
    $("#img-id-230").click(function(){
        $("#id-115").hide("slow");
    });
    $("#img-id-231").click(function(){
        $("#id-116").show("slow");
    });
    $("#img-id-232").click(function(){
        $("#id-116").hide("slow");
    });
    $("#img-id-233").click(function(){
        $("#id-117").show("slow");
    });
    $("#img-id-234").click(function(){
        $("#id-117").hide("slow");
    });
    $("#img-id-235").click(function(){
        $("#id-118").show("slow");
    });
    $("#img-id-236").click(function(){
        $("#id-118").hide("slow");
    });
    $("#img-id-237").click(function(){
        $("#id-119").show("slow");
    });
    $("#img-id-238").click(function(){
        $("#id-119").hide("slow");
    });
    $("#img-id-239").click(function(){
        $("#id-120").show("slow");
    });
    $("#img-id-240").click(function(){
        $("#id-120").hide("slow");
    });    
    $("#img-id-241").click(function(){
        $("#id-121").show("slow");
    });
    $("#img-id-242").click(function(){
        $("#id-121").hide("slow");
    });
    $("#img-id-243").click(function(){
        $("#id-122").show("slow");
    });
    $("#img-id-244").click(function(){
        $("#id-122").hide("slow");
    });
    $("#img-id-245").click(function(){
        $("#id-123").show("slow");
    });
    $("#img-id-246").click(function(){
        $("#id-123").hide("slow");
    });
    $("#img-id-247").click(function(){
        $("#id-124").show("slow");
    });
    $("#img-id-248").click(function(){
        $("#id-124").hide("slow");
    });
    $("#img-id-249").click(function(){
        $("#id-125").show("slow");
    });
    $("#img-id-250").click(function(){
        $("#id-125").hide("slow");
    });
    $("#img-id-251").click(function(){
        $("#id-126").show("slow");
    });
    $("#img-id-252").click(function(){
        $("#id-126").hide("slow");
    });
    $("#img-id-253").click(function(){
        $("#id-127").show("slow");
    });
    $("#img-id-254").click(function(){
        $("#id-127").hide("slow");
    });
    $("#img-id-255").click(function(){
        $("#id-128").show("slow");
    });
    $("#img-id-256").click(function(){
        $("#id-128").hide("slow");
    });
    $("#img-id-257").click(function(){
        $("#id-129").show("slow");
    });
    $("#img-id-258").click(function(){
        $("#id-129").hide("slow");
    });
    $("#img-id-259").click(function(){
        $("#id-130").show("slow");
    });
    $("#img-id-260").click(function(){
        $("#id-130").hide("slow");
    });
    $("#img-id-261").click(function(){
        $("#id-131").show("slow");
    });
    $("#img-id-262").click(function(){
        $("#id-131").hide("slow");
    });
    $("#img-id-263").click(function(){
        $("#id-132").show("slow");
    });
    $("#img-id-264").click(function(){
        $("#id-132").hide("slow");
    });
    $("#img-id-265").click(function(){
        $("#id-133").show("slow");
    });
    $("#img-id-266").click(function(){
        $("#id-133").hide("slow");
    });
    $("#img-id-267").click(function(){
        $("#id-134").show("slow");
    });
    $("#img-id-268").click(function(){
        $("#id-134").hide("slow");
    });
    $("#img-id-269").click(function(){
        $("#id-135").show("slow");
    });
    $("#img-id-270").click(function(){
        $("#id-135").hide("slow");
    });
    $("#img-id-271").click(function(){
        $("#id-136").show("slow");
    });
    $("#img-id-272").click(function(){
        $("#id-136").hide("slow");
    });
    $("#img-id-273").click(function(){
        $("#id-137").show("slow");
    });
    $("#img-id-274").click(function(){
        $("#id-137").hide("slow");
    });
    $("#img-id-275").click(function(){
        $("#id-138").show("slow");
    });
    $("#img-id-276").click(function(){
        $("#id-138").hide("slow");
    });
    $("#img-id-277").click(function(){
        $("#id-139").show("slow");
    });
    $("#img-id-278").click(function(){
        $("#id-139").hide("slow");
    });
    $("#img-id-279").click(function(){
        $("#id-140").show("slow");
    });
    $("#img-id-280").click(function(){
        $("#id-140").hide("slow");
    });
    $("#img-id-281").click(function(){
        $("#id-141").show("slow");
    });
    $("#img-id-282").click(function(){
        $("#id-141").hide("slow");
    });
    $("#img-id-283").click(function(){
        $("#id-142").show("slow");
    });
    $("#img-id-284").click(function(){
        $("#id-142").hide("slow");
    });
    $("#img-id-285").click(function(){
        $("#id-143").show("slow");
    });
    $("#img-id-286").click(function(){
        $("#id-143").hide("slow");
    });
    $("#img-id-287").click(function(){
        $("#id-144").show("slow");
    });
    $("#img-id-288").click(function(){
        $("#id-144").hide("slow");
    });
    $("#img-id-289").click(function(){
        $("#id-145").show("slow");
    });
    $("#img-id-290").click(function(){
        $("#id-145").hide("slow");
    });
    $("#img-id-291").click(function(){
        $("#id-146").show("slow");
    });
    $("#img-id-292").click(function(){
        $("#id-146").hide("slow");
    });
    $("#img-id-293").click(function(){
        $("#id-147").show("slow");
    });
    $("#img-id-294").click(function(){
        $("#id-147").hide("slow");
    });
    $("#img-id-295").click(function(){
        $("#id-148").show("slow");
    });
    $("#img-id-296").click(function(){
        $("#id-148").hide("slow");
    });
    $("#img-id-297").click(function(){
        $("#id-149").show("slow");
    });
    $("#img-id-298").click(function(){
        $("#id-149").hide("slow");
    });
    $("#img-id-299").click(function(){
        $("#id-150").show("slow");
    });
    $("#img-id-300").click(function(){
        $("#id-150").hide("slow");
    });
    
    $("#img-id-301").click(function(){
        $("#id-151").show("slow");
    });
    $("#img-id-302").click(function(){
        $("#id-151").hide("slow");
    });
    $("#img-id-303").click(function(){
        $("#id-152").show("slow");
    });
    $("#img-id-304").click(function(){
        $("#id-152").hide("slow");
    });
    $("#img-id-305").click(function(){
        $("#id-153").show("slow");
    });
    $("#img-id-306").click(function(){
        $("#id-153").hide("slow");
    });
    $("#img-id-307").click(function(){
        $("#id-154").show("slow");
    });
    $("#img-id-308").click(function(){
        $("#id-154").hide("slow");
    });
    $("#img-id-309").click(function(){
        $("#id-155").show("slow");
    });
    $("#img-id-310").click(function(){
        $("#id-155").hide("slow");
    });
    $("#img-id-311").click(function(){
        $("#id-156").show("slow");
    });
    $("#img-id-312").click(function(){
        $("#id-156").hide("slow");
    });
    $("#img-id-313").click(function(){
        $("#id-157").show("slow");
    });
    $("#img-id-314").click(function(){
        $("#id-157").hide("slow");
    });
    $("#img-id-315").click(function(){
        $("#id-158").show("slow");
    });
    $("#img-id-316").click(function(){
        $("#id-158").hide("slow");
    });
    $("#img-id-317").click(function(){
        $("#id-159").show("slow");
    });
    $("#img-id-318").click(function(){
        $("#id-159").hide("slow");
    });
    $("#img-id-319").click(function(){
        $("#id-160").show("slow");
    });
    $("#img-id-320").click(function(){
        $("#id-160").hide("slow");
    });
    $("#img-id-321").click(function(){
        $("#id-161").show("slow");
    });
    $("#img-id-322").click(function(){
        $("#id-161").hide("slow");
    });
    $("#img-id-323").click(function(){
        $("#id-162").show("slow");
    });
    $("#img-id-324").click(function(){
        $("#id-162").hide("slow");
    });
    $("#img-id-325").click(function(){
        $("#id-163").show("slow");
    });
    $("#img-id-326").click(function(){
        $("#id-163").hide("slow");
    });
    $("#img-id-327").click(function(){
        $("#id-164").show("slow");
    });
    $("#img-id-328").click(function(){
        $("#id-164").hide("slow");
    });
    $("#img-id-329").click(function(){
        $("#id-165").show("slow");
    });
    $("#img-id-330").click(function(){
        $("#id-165").hide("slow");
    });
    $("#img-id-331").click(function(){
        $("#id-166").show("slow");
    });
    $("#img-id-332").click(function(){
        $("#id-166").hide("slow");
    });
    $("#img-id-333").click(function(){
        $("#id-167").show("slow");
    });
    $("#img-id-334").click(function(){
        $("#id-167").hide("slow");
    });
    $("#img-id-335").click(function(){
        $("#id-168").show("slow");
    });
    $("#img-id-336").click(function(){
        $("#id-168").hide("slow");
    });
    $("#img-id-337").click(function(){
        $("#id-169").show("slow");
    });
    $("#img-id-338").click(function(){
        $("#id-169").hide("slow");
    });
    $("#img-id-339").click(function(){
        $("#id-170").show("slow");
    });
    $("#img-id-340").click(function(){
        $("#id-170").hide("slow");
    });
    $("#img-id-341").click(function(){
        $("#id-171").show("slow");
    });
    $("#img-id-342").click(function(){
        $("#id-171").hide("slow");
    });
    $("#img-id-343").click(function(){
        $("#id-172").show("slow");
    });
    $("#img-id-344").click(function(){
        $("#id-172").hide("slow");
    });
    $("#img-id-345").click(function(){
        $("#id-173").show("slow");
    });
    $("#img-id-346").click(function(){
        $("#id-173").hide("slow");
    });
    $("#img-id-347").click(function(){
        $("#id-174").show("slow");
    });
    $("#img-id-348").click(function(){
        $("#id-174").hide("slow");
    });
    $("#img-id-349").click(function(){
        $("#id-175").show("slow");
    });
    $("#img-id-350").click(function(){
        $("#id-175").hide("slow");
    });
    $("#img-id-351").click(function(){
        $("#id-176").show("slow");
    });
    $("#img-id-352").click(function(){
        $("#id-176").hide("slow");
    });
    $("#img-id-353").click(function(){
        $("#id-177").show("slow");
    });
    $("#img-id-354").click(function(){
        $("#id-177").hide("slow");
    });
    $("#img-id-355").click(function(){
        $("#id-178").show("slow");
    });
    $("#img-id-356").click(function(){
        $("#id-178").hide("slow");
    });
    $("#img-id-357").click(function(){
        $("#id-179").show("slow");
    });
    $("#img-id-358").click(function(){
        $("#id-179").hide("slow");
    });
    $("#img-id-359").click(function(){
        $("#id-180").show("slow");
    });
    $("#img-id-360").click(function(){
        $("#id-180").hide("slow");
    });
});